version: '2'
services:
  web:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/go-in-action/go/02_search_feeds
    working_dir: /go-in-action/go/02_search_feeds
    command: go run main.go
