version: '2'
services:
  web:
    restart: always
    build: .
    command: go run go/03_hello_world/hello.go
    ports:
      - "5000:5000"
    volumes:
      - .:/go-in-action
    working_dir: /go-in-action
